### ISSUE TITLE
gwan crashes when starting consensus

### ISSUE THREAD

**Issue by nymkappa** [wanchain/go-wanchain#10]
Hello,

I'm trying to run a local development chain using `gwan` on `sha3` branch but I can't manage to start it properly. I built `gwan` using `make release`. I'm using the creating binary `gwan-darwin-10.6-amd64`.

First error I got was

```
Fatal: Error starting protocol stack: database already contains an incompatible genesis block (have 2893a852a2fdec70, new ffcba984551d827c)
```

So far this is what I did:
```
joris@joriss-MacBook-Pro go-wanchain % mkdir local
joris@joriss-MacBook-Pro go-wanchain % cp genesis_example/genesisTestNet.json ./local 
joris@joriss-MacBook-Pro go-wanchain % ./gwan --datadir local init local/genesisTestNet.json 
WARN [06-10|19:50:31] No etherbase set and no accounts found as default 
INFO [06-10|19:50:31] Allocated cache and file handles         database=local/gwan/pos cache=16 handles=256
INFO [06-10|19:50:31] Allocated cache and file handles         database=local/gwan/rblocaldb cache=16 handles=256
INFO [06-10|19:50:31] Allocated cache and file handles         database=local/gwan/eplocaldb cache=16 handles=256
INFO [06-10|19:50:31] Allocated cache and file handles         database=/Users/joris/Documents/work/go-wanchain/local/gwan/chaindata cache=16 handles=16
INFO [06-10|19:50:31] Writing default  test net genesis block 
INFO [06-10|19:50:31] Successfully wrote genesis state         database=chaindata                                                    hash=0x2893a852a2fdec70cfb74307512489a2880c55703dcb623e3cf51300474af8d4
INFO [06-10|19:50:31] Allocated cache and file handles         database=/Users/joris/Documents/work/go-wanchain/local/gwan/lightchaindata cache=16 handles=16
INFO [06-10|19:50:32] Writing default  test net genesis block 
INFO [06-10|19:50:32] Successfully wrote genesis state         database=lightchaindata                                                    hash=0x2893a852a2fdec70cfb74307512489a2880c55703dcb623e3cf51300474af8d4
joris@joriss-MacBook-Pro go-wanchain % ./gwan --datadir local account new                   
WARN [06-10|19:51:00] No etherbase set and no accounts found as default 
INFO [06-10|19:51:00] Allocated cache and file handles         database=local/gwan/pos cache=16 handles=256
INFO [06-10|19:51:00] Allocated cache and file handles         database=local/gwan/rblocaldb cache=16 handles=256
INFO [06-10|19:51:00] Allocated cache and file handles         database=local/gwan/eplocaldb cache=16 handles=256
Your new account is locked with a password. Please give a password. Do not forget this password.
Passphrase: 
Repeat passphrase: 
Address: {d975dB4210C5FbB764d55fB60f2292569C321297}
joris@joriss-MacBook-Pro go-wanchain % ./gwan --datadir local account list
Account #1: {d975db4210c5fbb764d55fb60f2292569c321297} keystore:///Users/joris/Documents/work/go-wanchain/local/keystore/UTC--2021-06-10T10-51-32.997406000Z--d975db4210c5fbb764d55fb60f2292569c321297
joris@joriss-MacBook-Pro go-wanchain % cat local/genesisTestNet.json 
{
  "config": {
        "chainId": 3,
        "byzantiumBlock": 0
    },
  "alloc"      : {},
  "coinbase"   : "0x0000000000000000000000000000000000000000",
  "difficulty" : "0x20000",
  "extraData"  : "",
  "gasLimit"   : "0x2fefd8",
  "nonce"      : "0x000000000000000",
  "mixhash"    : "0x0000000000000000000000000000000000000000000000000000000000000000",
  "parentHash" : "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp"  : "0x00"
}
joris@joriss-MacBook-Pro go-wanchain % ./gwan --dev --datadir local --etherbase 0x9da26fc2e1d6ad9fdd46138906b0104ae68a65d8 --unlock d975db4210c5fbb764d55fb60f2292569c321297 --password ./pwdfile --mine --minerthreads 1 --rpc --rpcaddr 0.0.0.0 --rpcapi eth,personal,net,admin,wan,txpool 
 
INFO [06-10|19:55:22] Allocated cache and file handles         database=local/gwan/pos cache=16 handles=256
INFO [06-10|19:55:22] Allocated cache and file handles         database=local/gwan/rblocaldb cache=16 handles=256
INFO [06-10|19:55:22] Allocated cache and file handles         database=local/gwan/eplocaldb cache=16 handles=256
INFO [06-10|19:55:24] Unlocked account                         address=0xd975dB4210C5FbB764d55fB60f2292569C321297
INFO [06-10|19:55:24] Starting peer-to-peer node               instance=gwan/v2.2.1-beta.1/darwin-amd64/go1.13.4
INFO [06-10|19:55:24] Allocated cache and file handles         database=/Users/joris/Documents/work/go-wanchain/local/gwan/chaindata cache=128 handles=2048
WARN [06-10|19:55:24] Upgrading database to use lookup entries 
INFO [06-10|19:55:24] Database deduplication successful        deduped=0
Fatal: Error starting protocol stack: database already contains an incompatible genesis block (have 2893a852a2fdec70, new ffcba984551d827c)
joris@joriss-MacBook-Pro go-wanchain % 
```

So it seems that `gwan` is trying to re-initialize the chain even though I already initialized it. So I deleted the chain data an restarted the node. But now it crashes at start with a SIGSEV.

```
joris@joriss-MacBook-Pro go-wanchain % rm -rf local/gwan
joris@joriss-MacBook-Pro go-wanchain % ./gwan --dev --datadir local --etherbase 0x9da26fc2e1d6ad9fdd46138906b0104ae68a65d8 --unlock d975db4210c5fbb764d55fb60f2292569c321297 --password ./pwdfile --mine --minerthreads 1 --rpc --rpcaddr 0.0.0.0 --rpcapi eth,personal,net,admin,wan,txpool

INFO [06-10|20:03:27] Allocated cache and file handles         database=local/gwan/pos cache=16 handles=256
INFO [06-10|20:03:27] Allocated cache and file handles         database=local/gwan/rblocaldb cache=16 handles=256
INFO [06-10|20:03:27] Allocated cache and file handles         database=local/gwan/eplocaldb cache=16 handles=256
INFO [06-10|20:03:28] Unlocked account                         address=0xd975dB4210C5FbB764d55fB60f2292569C321297
INFO [06-10|20:03:28] Starting peer-to-peer node               instance=gwan/v2.2.1-beta.1/darwin-amd64/go1.13.4
INFO [06-10|20:03:28] Allocated cache and file handles         database=/Users/joris/Documents/work/go-wanchain/local/gwan/chaindata cache=128 handles=2048
INFO [06-10|20:03:28] Writing custom genesis block 
INFO [06-10|20:03:28] Initialised chain configuration          config="{ChainID: 1337 Byzantium: 0 Engine: ethash}"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4975340]

goroutine 1 [running]:
github.com/wanchain/go-wanchain/consensus/pluto.New(0x0, 0x51b58e0, 0xc00016f450, 0x3)
        /ext-go/1/src/github.com/wanchain/go-wanchain/consensus/pluto/pluto.go:238 +0x40
github.com/wanchain/go-wanchain/eth.New(0xc0004ac700, 0xc000336380, 0x4d5cbc0, 0xc0002c76e0, 0x400ecb8)
        /ext-go/1/src/github.com/wanchain/go-wanchain/eth/backend.go:122 +0x234
github.com/wanchain/go-wanchain/cmd/utils.RegisterEthService.func2(0xc0004ac700, 0xc0001ecc90, 0xc0002c78a8, 0x3, 0xc0002c7888)
        /ext-go/1/src/github.com/wanchain/go-wanchain/cmd/utils/flags.go:1110 +0x3d
github.com/wanchain/go-wanchain/node.(*Node).Start(0xc0000c4b40, 0x0, 0x0)
        /ext-go/1/src/github.com/wanchain/go-wanchain/node/node.go:175 +0x3d2
github.com/wanchain/go-wanchain/cmd/utils.StartNode(0xc0000c4b40)
        /ext-go/1/src/github.com/wanchain/go-wanchain/cmd/utils/cmd.go:62 +0x2f
main.startNode(0xc00010a6e0, 0xc0000c4b40)
        /ext-go/1/src/github.com/wanchain/go-wanchain/cmd/gwan/main.go:287 +0x259
main.geth(0xc00010a6e0, 0x4f69870, 0xb2d05e00)
        /ext-go/1/src/github.com/wanchain/go-wanchain/cmd/gwan/main.go:251 +0xf7
github.com/wanchain/go-wanchain/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x4beb040, 0x4f6b380, 0xc00010a6e0, 0xc0000b8de0, 0x0)
        /ext-go/1/src/github.com/wanchain/go-wanchain/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xc8
github.com/wanchain/go-wanchain/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0000ac4e0, 0xc000032120, 0x12, 0x12, 0x0, 0x0)
        /ext-go/1/src/github.com/wanchain/go-wanchain/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x58c
main.main()
        /ext-go/1/src/github.com/wanchain/go-wanchain/cmd/gwan/main.go:226 +0x55
joris@joriss-MacBook-Pro go-wanchain % 
```

So my question is. How can I manage to run a local chain using `gwan`, from `sha3` branch? Thank you.

**Comment by lolieatcat** [comment]
Hi, the first issue is you have different data on disk. the second issue is because after pos upgrade, gwan not support to use genesis json to start a private chain.

**Comment by lolieatcat** [comment]
you have to use the script and keystore in bootnode directory.  
https://github.com/wanchain/go-wanchain/blob/develop/bootnode/dev_run_bootnode_pluto_mac.sh
